name: Manual Fetch Comments

on:
  workflow_dispatch:

jobs:
  fetch-comments:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7

    - name: Install Octokit.rb
      run: gem install octokit

    - name: Fetch and Display Comments
      run: |
        require 'octokit'
        
        # Replace 'your_actual_token' with your GitHub personal access token
        client = Octokit::Client.new :access_token => 'ACCESS_TOKEN'

        # Replace 'alamzia23/demo-ci-cd' and 51984060 with your repository and pull request number
        client.issue_comments("alamzia23/demo-ci-cd", 51984060).each do |comment|
          username = comment[:user][:login]
          post_date = comment[:created_at]
          content = comment[:body]

          echo "${alamzia23} made a comment on ${post_date}. It says:\n'${content}'\n"
        done
