name: Merge PR to Int with "TESTED" Commits

on:
  pull_request:
    branches: [ Dev ]

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Check if any commit message contains "TESTED"
      - name: Check for "TESTED" in commit messages
        run: |
          git log --oneline | grep -i "TESTED" && exit 0 || exit 1

      # If "TESTED" found, merge the pull request
      - name: Merge pull request
        if: steps.check.exit_code == 0
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              merge_method: 'merge',
            });
          token: ${{ secrets.SECRET_KEY }}

      # If "TESTED" not found, comment on the pull request
      - name: Comment on pull request
        if: steps.check.exit_code != 0
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: 'Pull request cannot be merged automatically. Please add "TESTED" to a commit message.'
            });

