name: List Commits from Merged PRs

on:
  push:
    branches:
      - main

jobs:
  list-commits:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: git config --global user.email "you@example.com" && git config --global user.name "Your Name"

    - name: List Commits from Merged PRs
      run: |
        git log --merges --grep='TESTED' --pretty=format:"%H" | sort -u
        # for pr_commit in $(git log --merges --grep='TESTED' --pretty=format:"%H" | sort -u); do
         # echo "Commits for merged PR $pr_commit:"
          # git log --oneline $pr_commit^..$pr_commit
         # echo "----------------------------------------"
       # done
