name: Get Tested Commits

on:
  workflow_dispatch:

jobs:
  get_commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get merged pull requests
        id: get_merged_prs
        run: |
          stdout=$(curl -H "Authorization: token ${{ secrets.SECRET_KEY }}" \
            "https://api.github.com/repos/alamzia23/demo-ci-cd/pulls?state=closed")
          delimiter=$(openssl rand -hex 8)
          echo "OUT<<$delimiter" >> $GITHUB_OUTPUT
          echo "stdout=$stdout" >> $GITHUB_OUTPUT
          echo "$delimiter" >> $GITHUB_OUTPUT
      
      #- name: Parse merged pull requests
       # id: parse_merged_prs
       # run: |
       #   jq --raw-output '.[] | {pull_number: .number, commits: .commits}' <<< ${{ steps.get_merged_prs.outputs.stdout }}
      
      - name: Get commits with "TESTED" comment
        id: get_tested_commits
        run: |
          jq -r '.[] | select(.commits | any(.message | contains("TESTED") or any(.comments[].body | contains("TESTED")))) | .commits | map(.sha)' <<< ${{ steps.parse_merged_prs.outputs.stdout }}

      - name: Output commit SHAs
        run: |
          echo "Commits with 'TESTED' comment:"
          echo ${{ steps.get_tested_commits.outputs.stdout }}
          
      - name: Save commit SHAs to file
        if: github.event.inputs.save_file
        uses: actions/upload-artifact@v3
        with:
          name: tested-commits
          path: ${{ github.event.inputs.save_file }}
          content-type: text/plain

