name: Get Tested Commits

on:
  workflow_dispatch:

jobs:
  get_commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get merged pull requests
        id: get_merged_prs
        run: |
          # Fetch merged pull requests
          PRS=$(curl -s -H "Authorization: token ${{ secrets.SECCRETT_KEY }}" \
            "https://api.github.com/repos/alamzia23/demo-ci-cd/pulls?state=closed")
          echo "::set-output name=merged_prs::$(echo "$PRS")"

      - name: Filter PRs with "TESTED" comment
        id: filter_tested_prs
        run: |
          # Use jq to filter PRs with "TESTED" comment
          TESTED_PRS=$(echo "${{ steps.get_merged_prs.outputs.merged_prs }}" | jq -r '.[] | select(.comments | any(.body | contains("TESTED"))) | .number')
          echo "::set-output name=tested_prs::${TESTED_PRS}"

      - name: Output tested PRs
        run: |
          echo "Merged PRs with 'TESTED' comment:"
          echo "${{ steps.filter_tested_prs.outputs.tested_prs }}"

      - name: Save tested PRs to file
        if: github.event.inputs.save_file
        uses: actions/upload-artifact@v2
        with:
          name: tested-prs
          path: ${{ github.event.inputs.save_file }}
          content-type: text/plain
