name: Process Pull Request Comments

on:
  workflow_dispatch:  # Trigger manually

jobs:
  process_comments:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # Adjust if needed
      - run: gem install octokit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBS_TOKEN }}
          KEYWORD: 'TESTED'  # Add the keyword as an environment variable

      - name: Process comments (closed PRs)
        run: |
          ruby -e "require 'octokit'; client = Octokit::Client.new(:access_token => ENV['GITHUB_TOKEN']); client.pull_requests('${{ github.repository }}', state: 'closed').each { |pr| client.pull_request_comments('${{ github.repository }}', pr.number).each { |comment| if comment[:body].downcase.include?(ENV['TESTED'].downcase) then puts \"#{comment[:user][:login]} made a comment on #{comment[:created_at]} for the file called #{comment[:path]}, on line #{comment[:position]}. It says:\n'#{comment[:body]}'\n\" end } }"
